<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\html\login.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\html\login.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ESFE.GestionProductos.LN\ESFE.GestionProductos.LN.csproj" />
  </ItemGroup>

</Project>
